### ISSUE TITLE
Error sending notification

### ISSUE THREAD

**Issue by BogdanCondorachi** [youngcut/kirby-form-blocks#10]
I'm getting the following error when I'm submitting the form.

"Error sending notification: Call to a member function value() on null"

**Comment by BogdanCondorachi** [comment]
@renestalder I didn't do specifically anything, one day It just worked again. Surely there a problem in the plugin code but don't know what. Post in here #11 that you've got the same problem and maybe you could get to the bottom of with together with @youngcut

**Comment by renestalder** [comment]
@BogdanCondorachi Ah nice, didn't notice the second ticket. Will check there.
