### ISSUE TITLE
Remove inline styles from frontend markup

### ISSUE THREAD

**Issue by renestalder** [youngcut/kirby-form-blocks#12]
During implementation of #8 I noticed there are a couple of inline styles in form of a CSS grid. The problem with these are that they have the highest possible CSS selector specificity as they are inline and are therefore difficult to overwrite by plugin users. In addition, they are currently not optimized for smaller screens. It's just one big CSS grid.

Kirby encourages plugin authors to not include custom CSS or scripts to the frontend, that's why it doesn't come with an API to include CSS files (instead of WordPress, which will clutter your frontend with slow scripts and CSS files as more and more plugins get installed).

I therefore would suggest removing all inline styles and leave it up to the developer to style the form completely from scratch. Alternatively, you could provide a CSS file which can then manually be included via `css()` function.

**Comment by samnabi** [comment]
I agree, the grid class and inline styles should be removed. I would also recommend removing the `width` field from the default `customfields.yml` blueprint.

**Comment by youngcut** [comment]
@samnabi thanks for your input. It's done in Release V2.0:
- Inline styles removed
- width-field removed
(And many other things)
