### ISSUE TITLE
In Kirby v3.7.0.1, the Inbox is no longer displayed in the Drawer.

### ISSUE THREAD

**Issue by zweiwdesign** [youngcut/kirby-form-blocks#21]
After updating to Kirby v.3.7.0.1, the inbox is no longer displayed in the drawer. In version 3.6 this still works fine. Possibly it is due to the update of the UI?

**Comment by youngcut** [comment]
Thanks for your report. I could reproduce it. I open up a [ticket in the forum](https://forum.getkirby.com/t/k-items-not-working-since-kirby-3-7/25921). Hope the support-team of kirby knows a solution.

**Comment by youngcut** [comment]
Alright. It's fixed in v2.0.2!
