### ISSUE TITLE
Undefined variable $form

### ISSUE THREAD

**Issue by macx** [youngcut/kirby-form-blocks#23]
I installed Form-Blocks via composer, added the form block without any modifications and get an exception: `Undefined variable $form` in `kirby-form-blocks/snippets/blocks/form.php` on line 1.

![image](https://user-images.githubusercontent.com/84112/185175493-eb8ba10e-08ad-45f3-8d58-ee62d675fcf0.png)

**Comment by youngcut** [comment]
Hi. It's hard to reproduce this way. Let's see if we could figure out what it is by answering following questions:

Did you add the form-block anywhere on your site?
If yes, how?
Have you tried to delete ```site/plugins/kirby-form-blocks``` and reinstall via composer?
Is there other plugins installed on your site?
And the classic-one: What Kirby- and PHP-Version are you using?

**Comment by dinko** [comment]
Hey there, great plugin which I just wanted to add for a client.

However…unfortunately same issue here :/

Steps:

1. Installed via composer (also tried deleting and reinstalling)
2. Added `form` to some random block in a random blueprint
3. Added a form block a page using that blueprint
4. Without changing any parameters of the form block, saved it
5. Same error as for @macx 

> Did you add the form-block anywhere on your site?
> If yes, how?
As above, if that's what you meant.

> Have you tried to delete site/plugins/kirby-form-blocks and reinstall via composer?
yes

> Is there other plugins installed on your site?
Yes, many:
"bnomei/kirby3-autoid": "^2.0",
"bnomei/kirby3-fingerprint": "^3.0",
"hananils/kirby-colors": "^1.1",
"sylvainjule/matomo": "^1.0",
"flokosiol/focus": "^3.0",
"sylvainjule/previews": "^1.0",
"bnomei/kirby3-doctor": "^1.5",
"bnomei/kirby3-feed": "^1.5",
"microman/kirby-form-blocks": "^2.0"

> And the classic-one: What Kirby- and PHP-Version are you using?
PHP 7.4.29, Kirby 3.6.6.1

Hope it helps! Would be great to know the source of the issue…

**Comment by thusslack** [comment]
I had the same issue when using the plugin within a field of type _layout_. Since this field type has a block collection,  `$form` in the blocks template does not seem work, because there is only `$block` available?

At the top of `kirby-form-blocks/snippets/blocks/form.php` you could add `<?php $form = $block; ?>` and the template should work. Or is there another way to use it in this setup?

**Comment by dinko** [comment]
Thx, @thusslack, adding the initialization made it work! Would be awesome if you updated as described, @youngcut, or init some different way.

**Comment by youngcut** [comment]
Thank you guys for your support. Check the new version 2.0.3 and let me know, if the problem is solved.

**Comment by macx** [comment]
Unfortunately, it's not working: `Undefined variable $block`. But using `$form = $data;` is working on my environment. I use `$data` in many Snippets.

- PHP 8.1.9
- getkirby/cms 3.7.5

**Comment by youngcut** [comment]
@macx Thanks four your input.
@dinko Can you try and reply, if $data also work for you?

**Comment by dinko** [comment]
Doesn't work with `$form = $data;` for me, only if I assign it with the block object data. But imho, `$data` is an individual way of assigning and `$block` is what Kirby uses in all their default block snippets, so it's a bit like a reserved variable.

I'd suggest to assign `$block` to `$data` in your snippet and controller, @macx.

**Comment by macx** [comment]
That's right, @dinko. `$block` is the preferred way in Kirby. But this is not 100% clear because they often mention `$data` for all data passed to a snippet. I changed this to `$block`. @youngcut I think it's now fixed with the last version.
