### ISSUE TITLE
Comptability with Kirby 3.8

### ISSUE THREAD

**Issue by macx** [youngcut/kirby-form-blocks#25]
This plugin isn't compatible with Kirby 3.8 because of the use of `Kirby\Http\Server`, which is deprecated.

See [changelog](https://getkirby.com/releases/3.8#changes-deprecated)

**Comment by janstieler** [comment]
I got the error with `Class "Kirby\Http\Server" not found` also in the newest version of this plugin.

**Comment by youngcut** [comment]
> I got the error with `Class "Kirby\Http\Server" not found` also in the newest version of this plugin.

Do you update the plugin with the composer? I just updated the version. Could you try again and make sure your copy has the version 2.0.4.
