### ISSUE TITLE
Spam bot protection

### ISSUE THREAD

**Issue by bogdancondorachi** [youngcut/kirby-form-blocks#4]
Can you implement something for spam bot protection, maybe like an honeypot, captcha or something else? I love using your plugin for my projects but I also get lots of spam email's from bots and I'm looking for a solution about it. @youngcut

**Comment by youngcut** [comment]
Hi Bogdan. I have also considered a honeypot. I will see what I can do...

**Comment by youngcut** [comment]
I thing the easiest way (first aid) is to implement a honeypot. In the meanwhile you could add it manually in you template. ([See example from the Kirby-Website](https://getkirby.com/docs/cookbook/forms/basic-contact-form))
For a proper Implantation of a Capcha, it can be useful to program a form field for that. The user can then decide, which form should have this protection.

**Comment by S1SYPHOS** [comment]
For a captcha, see [php-simple-captcha](https://codeberg.org/S1SYPHOS/php-simple-captcha), which powers [uniform-simple-captcha](https://codeberg.org/refbw/uniform-simple-captcha) ..

**Comment by youngcut** [comment]
V2.0 included a honeypot. It's not the best protection, but for boor bots, it will do.
Simple Captcha is cool, but i don't know if visual impairment persons like that. 
I'm thinking of creating a Form field type for HCatpcha. 🤔 Someone help me?🥹

**Comment by S1SYPHOS** [comment]
Well, you may easily change colors & leave out some of the more aggressive effects in order to improve contrast and such - totally up to the devs - don't get me wrong, but captchas by themselves (sadly) are never accessible ..

Great plugin you whipped up there, though, congratulations!
