### ISSUE TITLE
"Eindeutiger Bezeichner" is not saved

### ISSUE THREAD

**Issue by renestalder** [youngcut/kirby-form-blocks#7]
Whenever I overwrite the field "Eindeutiger Bezeichner" with something else, then save (clicking the okay button of the form field), it is being reset to the automated slug of the field name. Using it in a German setup of Kirby.

On that note, it's also unclear to me if this field is reflected as the `name` attribute or the `autocomplete` attribute. The help of the field points to the `autocomplete` attribute value list on MDN. But that wouldn't make much sense for me, considering that these values are not meant to be unique and are solely for giving the browser autocomplete hints. in that sense, there probably should be two different fields, one for setting the unique name and one for choosing an autocomplete value with a select.

**Comment by youngcut** [comment]
Thanks for your input.
The field "Eindeutiger Bezeichner" is a slug-field (released in Kirby 3.6). There is a bug in this field which i'm on it to resolve it with the Kirby core team. There's already some workarounds [here](https://github.com/getkirby/kirby/issues/3940).

That's right. I wanted to give the user the possibility to influence the auto-completion in a simple way.
I think most browsers already determine the autocompletion from the ID or the name attribute. I think we could remove the autocomplete attribute from the template.
What do you think? And if the autocomplete field would have to be a dropdown, which could take extremely much time.

**Comment by renestalder** [comment]
> I think most browsers already determine the autocompletion from the ID or the name attribute

I'm not aware of this, but that's possible. I set them manually most of the time, so I can sure any password managers will for sure pick it up correctly.

> And if the autocomplete field would have to be a dropdown, which could take extremely much time.

It could also be a simple text field. The idea with the select came from the fact, that we would have the possible list of values already at hand. But yes, maybe that field would be too long anyway. Alternatively, a simple text field. Or a text field with a [data list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist). But my point is, that it would be great to have a way to overwrite the autocomplete value independent of the `name` or ID attribute.

**Comment by youngcut** [comment]
The issue with the [buggy slug field](https://github.com/getkirby/kirby/issues/3940) ist still open by kirby. I solved it whit the wizard im V2.0.
